[package]
edition = "2021"
name = "pmevm"
version = "0.0.0"
publish = false

[workspace]
members = [
  "backend"
]

[features]
default = ["debug"]
debug = ["panicking/std"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[dependencies]
composable-allocators = "0.1.1"
exit-no-std = "0.1.0"
panicking = { version = "0.2.0", default-features = false }
pmevm-backend = { path = "backend" }
tuifw-screen = "0.13.5"
tuifw-window = "0.13.5"
