name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          triple: x86_64-unknown-linux-gnu
        - os: windows-latest
          triple: x86_64-pc-windows-msvc
        - os: macOS-latest
          triple: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add rust-src --toolchain nightly-${{ matrix.triple }}"
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose --workspace"
    - run: "cargo test --verbose --workspace"
    - run: "cargo build --verbose --workspace --release"
    - run: "cargo outdated --verbose --workspace --aggresssive --root-deps-only --exit-code 1"
    - run: "cargo clippy --verbose --workspace"
    - run: "cargo +nightly build --verbose -Z build-std=core,alloc,panic_abort -Z build-std-features=panic_immediate_abort --target=${{ matrix.triple }} --no-default-features --release"
  x86:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          target: i686-unknown-linux-gnu
        - os: ubuntu-latest
          target: i686-pc-windows-gnu
        - os: windows-latest
          triple: i686-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup target add ${{ matrix.target }}"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose --workspace --target=${{ matrix.target }}"
